# Generated by Django 3.1 on 2020-08-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='progress',
            new_name='progress_test',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='test',
        ),
        migrations.AddField(
            model_name='teachers',
            name='progress_tutorial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='test_1',
            field=models.CharField(choices=[('Taken', 'Taken'), ('Not Taken', 'Not Taken')], default='Not Taken', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='test_2',
            field=models.CharField(choices=[('Taken', 'Taken'), ('Not Taken', 'Not Taken')], default='Not Taken', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='test_3',
            field=models.CharField(choices=[('Taken', 'Taken'), ('Not Taken', 'Not Taken')], default='Not Taken', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='test_4',
            field=models.CharField(choices=[('Taken', 'Taken'), ('Not Taken', 'Not Taken')], default='Not Taken', max_length=100),
        ),
    ]
