
# Generated by Django 3.0.8 on 2020-08-08 18:12

# Generated by Django 3.1 on 2020-08-08 17:13


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20200808_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text="Please don't exceed 450 characters.", max_length=1000)),

                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teachers')),

                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers')),

            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
    ]
