# Generated by Django 3.1 on 2020-08-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='reply',
            field=models.TextField(blank=True, help_text="Please don't exceed 450 characters.", max_length=1000, null=True),
        ),
    ]
