# Generated by Django 3.0.8 on 2020-08-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0002_auto_20200808_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
