# Generated by Django 3.0.8 on 2020-08-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0003_schools_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
