# Generated by Django 3.0.8 on 2020-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0004_auto_20200808_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
