# Generated by Django 3.0.8 on 2020-08-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0005_auto_20200808_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
