# Generated by Django 3.0.8 on 2020-08-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0006_auto_20200808_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredSchools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='schools',
            name='location',
        ),
    ]
