# Generated by Django 3.0.8 on 2020-08-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_assign_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='manager',
        ),
    ]
